### ISSUE TITLE
Hebrew translation suggestions

### ISSUE THREAD

**Issue by motiko** [sergeicodes/a11ymyths#21]
![image](https://user-images.githubusercontent.com/875618/144885718-da57aa16-ccbd-49bc-979f-2be57d55110c.png)
הופרך
sounds more direct
![image](https://user-images.githubusercontent.com/875618/144885975-70a6eafb-c1ec-4933-a1a0-e665d005bb55.png)
redundant point in end of title
![image](https://user-images.githubusercontent.com/875618/144886260-b4f491d9-f075-40f0-8525-1f49c15ed85c.png)
לאנשי - לאנשים
![image](https://user-images.githubusercontent.com/875618/144886602-11016a3f-161a-44d9-881f-3035e80e2cd3.png)
נגישות היא תהליך מתמשך -
הנגשה זה תהליך מתמשך -
![image](https://user-images.githubusercontent.com/875618/144886909-4472ff40-eaad-4e4e-97b9-e227fe170def.png)
שתף עם המנהל שלך
(should have a "share" link?)

**Comment by sergeicodes** [comment]
Thanks for feedback @motiko! Share link will be done later.
