### ISSUE TITLE
[es] Update translations

### ISSUE THREAD

**Issue by sergeicodes** [sergeicodes/a11ymyths#34]
Text changes:

- `h1`: Accessibility Myths
- `Myth 6`: Web accessibility is just a developer's responsibility
- `Myth 9`: Accessibility can be fixed by the accessibility overlay
- `Myth 11`: Accessibility is only for blind users
- `Myth 18`: Accessibility is like a feature - you do it once and then you have it

**Comment by sergeicodes** [comment]
Hi @pazguille, I updated some text, would you find time to translate it?

**Comment by pazguille** [comment]
#47
