### ISSUE TITLE
[pt-br] Update translations

### ISSUE THREAD

**Issue by sergeicodes** [sergeicodes/a11ymyths#38]
Text changes:

- `h1`: Accessibility Myths
- `Myth 6`: Web accessibility is just a developer's responsibility
- `Myth 9`: Accessibility can be fixed by the accessibility overlay
- `Myth 11`: Accessibility is only for blind users
- `Myth 18`: Accessibility is like a feature - you do it once and then you have it

**Comment by sergeicodes** [comment]
Hi @felipegenuino, I updated some text, would you find time to translate it?

**Comment by felipegenuino** [comment]
Yes today I update translations

Em sex, 31 de dez de 2021 08:24, Sergei Kriger ***@***.***>
escreveu:

**Comment by felipegenuino** [comment]
@sergeicodes I finished the translation update. As I had already left with context, in this update it was only necessary to update the h1 title.
