### ISSUE TITLE
Change reference link to ARIA rule

### ISSUE THREAD

**Issue by stevefaulkner** [sergeicodes/a11ymyths#4]
I suggest that you change the link from a derivative, commercial accessibility company one to the  primary W3C source. 

`but the golden rule of ARIA is "Don't Use ARIA". `

current link: https://www.deque.com/blog/top-5-rules-of-aria/
Original source link: https://w3c.github.io/using-aria/#notes2

**Comment by sergeicodes** [comment]
Hi @stevefaulkner, thanks for the suggestion. Fair point, just changed the link ✅
